//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSenderApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Schedule_AssignStudent
    {
        public int Schedule_AssignStuID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> RegistrationID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<bool> Entry_Confirmation { get; set; }
        public Nullable<bool> Exit_Confirmation { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Is_Abs_SMS { get; set; }
        public Nullable<bool> Is_Late_SMS { get; set; }
    
        public virtual Attendance_Schedule Attendance_Schedule { get; set; }
    }
}
