//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSenderApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Student
    {
        public int AttendanceStudentID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public int RegistrationID { get; set; }
        public Nullable<int> EducationYearID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> StudentClassID { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public Nullable<int> TotalPresent { get; set; }
        public Nullable<int> TotalAbsent { get; set; }
        public Nullable<int> TotalLate { get; set; }
        public Nullable<int> TotalLeave { get; set; }
        public Nullable<int> TotalBunk { get; set; }
        public Nullable<int> CumulativeNameID { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public Nullable<int> TotalLateAbs { get; set; }
    }
}
