//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSenderApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Attendance_Report
    {
        public int Employee_Attendance_ReportID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> RegistrationID { get; set; }
        public Nullable<int> EducationYearID { get; set; }
        public int EmployeeID { get; set; }
        public string ReportName { get; set; }
        public Nullable<int> Total_WorkingDays { get; set; }
        public Nullable<int> Total_Present { get; set; }
        public Nullable<int> Total_Absent { get; set; }
        public Nullable<int> Total_Late { get; set; }
        public Nullable<int> Total_Leave { get; set; }
        public Nullable<System.DateTime> Report_StartDate { get; set; }
        public Nullable<System.DateTime> Report_EndDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
