//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSenderApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Recharge_Record
    {
        public int SMS_Recharge_RecordID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> RechargeSMS { get; set; }
        public Nullable<double> PerSMS_Price { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
    }
}
