//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSenderApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Attendance_Stu_Setting
    {
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string StudentsName { get; set; }
        public string SMSPhoneNo { get; set; }
        public Nullable<bool> Entry_Confirmation { get; set; }
        public Nullable<bool> Exit_Confirmation { get; set; }
        public Nullable<bool> Is_Abs_SMS { get; set; }
        public Nullable<bool> Is_Late_SMS { get; set; }
        public Nullable<System.TimeSpan> LateEntryTime { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    }
}
