//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSenderApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Emp_Info
    {
        public Nullable<int> DeviceID { get; set; }
        public int SchoolID { get; set; }
        public string Job_Status { get; set; }
        public int EmployeeID { get; set; }
        public string ID { get; set; }
        public string EmployeeType { get; set; }
        public string Permanent_Temporary { get; set; }
        public string Bank_AccNo { get; set; }
        public string Work_Time_Basis { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Time_Basis_Type { get; set; }
        public string RFID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public string Phone { get; set; }
        public byte[] Image { get; set; }
    }
}
